### PR TITLE
Normalize translations

### PR DESCRIPTION
**Pull request by coorasse**
Hi everyone,
follow up from https://github.com/solidusio/solidus_i18n/pull/146.
I'd like to check for the translation files to be normalized using the `i18n-tasks check-normalized` task.
I added it to the Travis configuration and I simply ran `i18n-tasks normalize` on all translation files.
No manual work has been made in this PR, all changes to the files have been done by the normalize task. I add this information to simplify the code review because the changes are many.
One note: the `normalize` task adds an empty space on keys without a value ([see here](https://github.com/solidusio/solidus_i18n/compare/master...normalize_translations#diff-c457e175aa3dd4d9749b57f51813f4d3R16)). 
I am asking myself why do we have keys without value? is there a reasoning behind that or can we simply remove them? In case we want to keep them we would have to live with the empty space.
This check seems the most interesting at the moment because this gem is not covered (of course) by a lot of tests. Some improvements on this side will come in a separate PR.

### CODE REVIEW

**Comment by coorasse** [comment]
Related issue: https://github.com/glebm/i18n-tasks/issues/319

**Comment by kennyadsl** [comment]
I think the empty keys are there because someone originally copied the en version (from Solidus core). Of course, there's no reason to keep them at this point since the core file is out of sync.

**Comment by coorasse** [comment]
Currently `bundle exec i18n-tasks check-normalized` behaves differently locally and on TravisCI. I need to investigate the issue.

**Comment by kennyadsl** [comment]
Closing this one, but thanks for the effort Ale!

**Pull request closed without merging**
